print("CALCULATE Function")
num1 = int(input("Insert Number 1 : "))
num2 = int(input("Insert Number 2 : "))
print(num1, "+", num2, "= ", num1+num2)
print(num1, "-", num2, "= ", num1-num2)
print(num1, "*", num2, "= ", num1*num2)
print(num1, "/", num2, "= ", num1/num2)
